apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-my5grantester
  namespace: open5gs
  labels:
    epc-mode: my5grantester
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: my5grantester
  template:
    metadata:
      labels:
        epc-mode: my5grantester
    spec:
      nodeSelector:
          kubernetes.io/arch: amd64
          kubernetes.io/hostname: molejo
      containers:
        - name: my5grantester
          image: 00275559/my5grantester:latest
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN"]
      volumes:  
        - name: open5gs-my5grantester-config
          configMap:
            name: open5gs-my5grantester-config
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun

